# Copyright (c) 2026 ADBC Drivers Contributors
# Licensed under the Apache License, Version 2.0.

[package]
name = "sedona-adbc"
version = "0.5.0"
license = "Apache-2.0"
keywords = ["geospatial", "gis", "spatial", "datafusion", "arrow"]
categories = ["science::geo", "database"]
homepage = "https://github.com/apache/sedona-db"
repository = "https://github.com/adbc-drivers/sedonadb"
description = "ADBC driver for Apache SedonaDB"
readme = "README.md"
edition = "2024"
rust-version = "1.88.0"

[lints.clippy]
result_large_err = "allow"

[dependencies]
adbc_core = ">=0.24.0"
adbc_ffi = ">=0.24.0"
arrow-array = "58.3.0"
arrow-schema = "58.3.0"
datafusion = { version = "54.1.0", default-features = false }
futures = "0.3"
sedona = { git = "https://github.com/apache/sedona-db.git", rev = "242e4ffe329c36dead87f163331d3041409e7aac" }
sedona-extension = { git = "https://github.com/apache/sedona-db.git", rev = "242e4ffe329c36dead87f163331d3041409e7aac" }
tokio = { version = "1.52", features = ["rt-multi-thread"] }
